---
reponame: "code.arista.io/eos/tools/eext-bus"
description: >-
  This is a BUS to work with the eext tool.

users:
  supervisor: rganesan@arista.com
  maintainers:
    - aajith@arista.com

x-bar:
  version: production

x-github-bridge:
  reviews:
    - image: test
      events:
        - type: pull_request
        - type: push
          branch-re: "^main$|^eos-trunk$|.*-rel$"
